"""update tag model name should be unique

Revision ID: 0dd7f5e260da
Revises: 682356cc0736
Create Date: 2022-09-29 09:31:20.265526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0dd7f5e260da"
down_revision = "682356cc0736"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tag", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag", type_="unique")
    # ### end Alembic commands ###
