"""relationship

Revision ID: 682356cc0736
Revises: 4457373f33a8
Create Date: 2022-09-28 11:00:04.382844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "682356cc0736"
down_revision = "4457373f33a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_tag",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "post_id"),
    )
    op.drop_table("tags")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["post.id"], name="tags_post_id_fkey"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], name="tags_tag_id_fkey"),
        sa.PrimaryKeyConstraint("tag_id", "post_id", name="tags_pkey"),
    )
    op.drop_table("post_tag")
    # ### end Alembic commands ###
